# Generated by Django 3.1.6 on 2021-03-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('products', models.TextField(blank=True, verbose_name='Продукты')),
                ('recipe', models.TextField(blank=True, verbose_name='Рецепт')),
                ('calories', models.CharField(max_length=10, verbose_name='Калорийность')),
                ('time', models.CharField(max_length=4, verbose_name='Время приготовления, мин')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публиковать')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
